### ISSUE TITLE
limit and offset together 

### ISSUE THREAD

**Issue by anibalardid** [cloudblue/javascript-rql#5]
Hi ! 
I'm testing your plugin/extension.
I notice that you use limit and offset separated : **limit=10, offset=0**.
But in the rql way, they need to stay together: **limit(0,10)**.

Are there any way to fix it ? 

And something similar with "sort" ... you use $ordering ... but the correct string is "sort" , using **sort(+name)** for example

Best regards !

**Comment by borzovplus** [comment]
Hello!
Will be fixed in https://github.com/cloudblue/javascript-rql/pull/6

**Comment by borzovplus** [comment]
> Hi !
> I'm testing your plugin/extension.
> I notice that you use limit and offset separated : **limit=10, offset=0**.
> But in the rql way, they need to stay together: **limit(0,10)**.
> 
> Are there any way to fix it ?
> 
> And something similar with "sort" ... you use $ordering ... but the correct string is "sort" , using **sort(+name)** for example
> 
> Best regards !

Hello!
Will be fixed in #6

**Comment by anibalardid** [comment]
THANKS A LOT !!!
